### ISSUE TITLE
Creation of config directory fails on Windows 7

### ISSUE THREAD

**Issue by xrotwang** [imeji-community/pyimeji#12]

**Comment by xrotwang** [comment]
Considering that [the config directory on Windows may require creating two new directories](https://github.com/ActiveState/appdirs/blob/9c93e5e0e96cef5837b4fc906f35b8c0bda87924/appdirs.py#L71), the call to create it should use `os.makedirs` rather than `os.mkdir`.

**Comment by FelsyWaschbaer** [comment]
With manually creating a config file C:\Users\<username>\AppData\Local\<AppAuthor>\<AppName>\config.ini everything works fine.

**Comment by xrotwang** [comment]
Ok. The proposed change [made it into release v0.3](https://github.com/imeji-community/pyimeji/blob/65963ebb9877783621061440524e6eff4ac46de2/pyimeji/config.py#L29), so I'd consider this issue solved.
