### ISSUE TITLE
Passing through value of "exceptionReports"

### ISSUE THREAD

**Issue by ioverka** [imeji-community/pyimeji#16]
in case of an error, the response body includes some more details, e.g.
{
  "error": {
    "code": "1404",
    "title": "Not Found",
    "message": "1404-message",
    "exceptionReport": "Resource xxx not found!"
  }
}

I would like to reuse the value of exceptionReport, but it looks like the AssertationError raised currentl doesn't include the details from the response body.

**Comment by xrotwang** [comment]
I see two options:

1. Just pass the response text to `AssertionError` here: https://github.com/imeji-community/pyimeji/blob/master/pyimeji/api.py#L94
2. Create a custom `Error` class which could hold the parsed JSON response object.

I guess, option 2 would be preferable. Pull request anyone?

**Comment by ioverka** [comment]
Thanks! Exactly, option 2 would be preferable, but my knowledge probably restricts me to option 1 ;)

**Comment by xrotwang** [comment]
@ioverka Does [this](https://github.com/imeji-community/pyimeji/pull/17) solve your problem?

**Comment by ioverka** [comment]
@xrotwang Thanks so much, Robert! Yes it does, but I failed installing the lateste pyimeji version via pip install pyimeji --upgrade. Afterwards, the system states it is "pyimeji-1.0.0", but ImejiError is still not defined.

**Comment by xrotwang** [comment]
@ioverka Oh, that's because it isn't released yet :) For some reason I though you were [installing](http://pyimeji.readthedocs.org/en/latest/tutorial.html#installation) from a repository clone. Should I release as is or do you want to try out the install-from-github first?

**Comment by ioverka** [comment]
@xrotwang It works like a charm on my local installation, please release it :D

**Comment by xrotwang** [comment]
voila: https://pypi.python.org/pypi/pyimeji/1.1.0

**Comment by ioverka** [comment]
yay!
